### ISSUE TITLE
Looking for maintainers

### ISSUE THREAD

**Issue by jeromer** [belogik/goes#40]
I do not have time to properly maintain this library anymore. Would someone be interested in taking over this project ?

**Comment by pib** [comment]
I'm potentially interested in taking over maintenance or helping with maintenance. What sort of hand-off do you have in mind? Who actually owns the "belogik" organization on GitHub?

**Comment by jeromer** [comment]
I own the "belogik" organisation. However "belogik" is a registered trademark.

I am wondering if I could simply rename the "belogik" organisation to something else, and then transfer this repo to you.

**Comment by pib** [comment]
That would work. It would also probably be nice for existing users if the github.com/belogik/goes URL continued to work, perhaps pointing to a copy of the existing code so it didn't break anything, with a note at the top indicating the new home of the project.

**Comment by jeromer** [comment]
Sounds good. How about forking this repo in your account so I can add a big fat note about the new home of the project in the README ?

**Comment by pib** [comment]
@jeromer I've forked it to the https://github.com/OwnLocal/goes, which is where I will maintain it going forward.

**Comment by jeromer** [comment]
> @jeromer I've forked it to the https://github.com/OwnLocal/goes, which is where I will maintain it going forward.

Great I will put a big fat message in the README then.

> Also: sorry for the long time to reply, but I was on vacation for the last two weeks and didn't have much computer time between trips to the beach

No worries :)
